#!/bin/bash

# Required because cmake root isn't git root in this example
CLANG_FORMAT_BIN=$1
GIT_ROOT="$(git rev-parse --show-toplevel)"

pushd "${GIT_ROOT}" > /dev/null || exit

{
    git status --porcelain \
	| grep -E '.*\.cpp|.*\.h|.*\.cxx|.*\.hxx|.*\.hpp|.*\.cc' \
	| awk -F " " '{print $NF}' \
	| xargs -r "${CLANG_FORMAT_BIN}" -style=file -output-replacements-xml \
	| grep "replacement offset" 2>&1
} > /dev/null

RET="$?"
popd > /dev/null || exit

exit "${RET}"
